POST http://localhost:3007/tasks/
Content-Type: application/json

{
    "username": "praneetha",
    "password": "rak@1237ta",
    "emailAddress":"rakeshchr17@gmail.com"
}


###
POST  http://localhost:3007/login/ 
Content-Type: application/json

{
   "username": "rakeshChall",
    "password": "rak@1237t"
}

###

POST http://localhost:3007/productDetails/
Content-Type: application/json

{
    "category": "Clothings",
    "productName": "Lensckart",
    "couponCode" :"4FG7904VH",
    "description": "Some description text",
    "imageUrl": "https://example.com/image.jpg"
}
###

GET http://localhost:3007/cards/

####


POST http://localhost:3007/verify-otp/
Content-Type: application/json

{
    "otp":800859
}